### ISSUE TITLE
Virus warning v0.88 CJIO

### ISSUE THREAD

**Issue by kad-vestjg** [cityjson/cjio_dbexport#33]
* cjio_dbexport version: 0.88
* Python version: not applicable
* Operating System: Windows 10

### Description

The downloaded zip-file for the compiled version of CJIO (from the releases page) is said to contain a trojan horse (cf: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fWacatac.B!ml&threatid=2147735503) and can not be opened (or the executable executed) on Windows 10

**Comment by balazsdukai** [comment]
Hm, that's not good, thanks for reporting. I'll look into it.

**Comment by kad-vestjg** [comment]
@balazsdukai, I have problems here with proxies that have severe limitations in which applications are allowed to communicate with the outside world, so pip throws all kinds of errors. In the meanwhile the viruschecker on the computers here has been updated, and now the zip-file is downloaded without errors and I can open the executable. So: problem solved! Thank you!

(I'll still get in touch with the network-IT-guys here in order to get pip working through our proxyservers, but that is another issue, that will probably take a while to be solved :-( )
